CREATE TABLE 'products' (
'id' INTEGER DEFAULT NULL PRIMARY KEY,
'title' NVARCHAR(256) DEFAULT NULL,
'price' DECIMAL(19,6) DEFAULT NULL,
'description' NVARCHAR(512) DEFAULT NULL
);

CREATE TABLE 'images' (
'id' INTEGER DEFAULT NULL PRIMARY KEY,
'product_id' INTEGER DEFAULT NULL REFERENCES 'products' ('id'),
'src' TEXT DEFAULT NULL
);